"""Default IOP execution order for darktable 4.6.x (iop_order_version=2).

This list is extracted from a neutral XMP generated by darktable 4.6.1.
Module execution goes from index 0 (first applied) to end.
Used to insert new modules at the correct pipeline position.
"""
from __future__ import annotations


# Canonical order from darktable 4.6 src/iop/iop_order.c
# Only the modules we care about are listed; others are placed at end.
_DEFAULT_ORDER: list[str] = [
    "rawprepare",
    "invert",
    "temperature",
    "highlights",
    "hotpixels",
    "rawdenoise",
    "demosaic",
    "denoiseprofile",
    "bilateral",
    "rotatepixels",
    "scalepixels",
    "lens",
    "ashift",
    "liquify",
    "spots",
    "retouch",
    "exposure",
    "mask_manager",
    "hazeremoval",
    "channelmixerrgb",
    "colorreconstruct",
    "colorchecker",
    "defringe",
    "equalizer",
    "vibrance",
    "colorbalancergb",
    "colorbalance",
    "colorzones",
    "lowpass",
    "highpass",
    "sharpen",
    "diffuse",
    "lut3d",
    "colisa",
    "filmicrgb",
    "filmic",
    "sigmoid",
    "toneequal",
    "levels",
    "rgblevels",
    "rgbcurve",
    "basecurve",
    "tonecurve",
    "vignette",
    "grain",
    "bloom",
    "colorize",
    "lowlight",
    "monochrome",
    "borders",
    "watermark",
    "nlmeans",
    "cacorrect",
    "censorize",
    "atrous",
    "rawoverexposed",
    "overexposed",
    "dither",
    "clahe",
    "finalscale",
    "clipping",
    "flip",
    "output_color",
    "gamma",
]


def default_iop_order() -> list[str]:
    return list(_DEFAULT_ORDER)


def insert_position(order: list[str], operation: str) -> int:
    """Return the index in `order` after which `operation` should appear."""
    try:
        return order.index(operation)
    except ValueError:
        return len(order)
